name: Build Lime3DS

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget gnupg build-essential

    - name: Install Emscripten
      run: |
        git clone https://github.com/emscripten-core/emsdk.git
        cd emsdk
        ./emsdk install latest
        ./emsdk activate latest
        echo "source $(pwd)/emsdk_env.sh" >> $GITHUB_ENV

    - name: Create dist directory
      run: mkdir -p dist

    - name: Compile to .so
      run: |
        source ./emsdk/emsdk_env.sh
        emcc -O3 -s
