name: Build Lime3DS

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget gnupg build-essential

    - name: Install Emscripten
      run: |
        git clone https://github.com/emscripten-core/emsdk.git
        cd emsdk
        ./emsdk install latest
        ./emsdk activate latest

    - name: Create directories
      run: |
        mkdir -p dist
        mkdir -p build

    - name: Create C++ wrapper
      run: |
        echo '#include <emscripten.h>' > build/wrapper.cpp
        echo 'extern "C" {' >> build/wrapper.cpp
        echo 'void EMSCRIPTEN_KEEPALIVE run_js() {' >> build/wrapper.cpp
        echo '  // Call your JavaScript function here' >> build/wrapper.cpp
        echo '}' >> build/wrapper.cpp
        echo '}' >> build/wrapper.cpp

    - name: Compile to .so
      run: |
        source emsdk/emsdk_env.sh
        emcc -O3 -s WASM=1 -s SIDE_MODULE=1 -o dist/lime3ds.so build/wrapper.cpp

    - name: Install devkitPro
      run: |
        wget https://apt.devkitpro.org/install-devkitpro-pacman
        chmod +x install-devkitpro-pacman
        echo "Y" | sudo ./install-devkitpro-pacman
        sudo dkp-pacman -Sy --noconfirm
        sudo dkp-pacman -S switch-dev --noconfirm

    - name: Create build directory for .nro
      run: mkdir -p build/nro

    - name: Copy JavaScript files for .nro
      run: cp resources/scripts/htmlimporter.js build/nro/

    - name: Create Makefile for .nro
      run: |
        echo 'TARGET = lime3ds' > build/nro/Makefile
        echo 'BUILD = build' >> build/nro/Makefile
        echo 'SOURCES = .' >> build/nro/Makefile
        echo 'INCLUDES = .' >> build/nro/Makefile
        echo 'LIBS = -lnx' >> build/nro/Makefile
        echo 'include $(DEVKITPRO)/libnx/switch_rules' >> build/nro/Makefile
        echo '$(BUILD)/$(TARGET).nro: $(BUILD)/$(TARGET).elf' >> build/nro/Makefile

    - name: Compile to .nro
      run: |
        cd build/nro
        make

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Lime3DS
        path: dist/
