name: Build Lime3DS

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install devkitPro
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget https://apt.devkitpro.org/install-devkitpro-pacman
        chmod +x install-devkitpro-pacman
        sudo ./install-devkitpro-pacman
        sudo dkp-pacman -Syu
        sudo dkp-pacman -S switch-dev

    - name: Create build directory
      run: mkdir -p build

    - name: Copy JavaScript files
      run: cp resources/scripts/htmlimporter.js build/

    - name: Compile to .nro
      run: |
        # Add your specific commands to compile to .nro here
        # Example: Use nx-hbmenu or other tools to package the JavaScript as a homebrew app

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Lime3DS
        path: build/
