name: Build Lime3DS
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget gnupg build-essential
    - name: Install Emscripten
      run: |
        git clone https://github.com/emscripten-core/emsdk.git
        cd emsdk
        ./emsdk install latest
        ./emsdk activate latest
    - name: Create directories
      run: |
        mkdir -p dist
        mkdir -p build
        mkdir -p build/nro
    - name: Create C++ wrapper
      run: |
        echo '#include <emscripten.h>' > build/wrapper.cpp
        echo 'extern "C" {' >> build/wrapper.cpp
        echo 'void EMSCRIPTEN_KEEPALIVE run_js() {' >> build/wrapper.cpp
        echo '  // Call your JavaScript function here' >> build/wrapper.cpp
        echo '}' >> build/wrapper.cpp
        echo '}' >> build/wrapper.cpp
    - name: Compile to .so
      run: |
        source emsdk/emsdk_env.sh
        emcc -O3 -s WASM=1 -s SIDE_MODULE=1 -o dist/lime3ds.so build/wrapper.cpp
    - name: Use devkitPro Docker image
      run: |
        docker run --rm -v $(pwd):/workspace -w /workspace devkitpro/devkita64:latest /bin/bash -c "
          dkp-pacman -Sy --noconfirm &&
          dkp-pacman -S switch-dev --noconfirm &&
          dkp-pacman -S libnx --noconfirm &&
          mkdir -p build/nro &&
          cp resources/scripts/htmlimporter.js build/nro/ &&
          echo 'TARGET = lime3ds' > build/nro/Makefile &&
          echo 'BUILD = build' >> build/nro/Makefile &&
          echo 'SOURCES = .' >> build/nro/Makefile &&
          echo 'INCLUDES = .' >> build/nro/Makefile &&
          echo 'LIBS = -lnx' >> build/nro/Makefile &&
          echo 'include /opt/devkitpro/libnx/switch_rules' >> build/nro/Makefile &&
          echo '$(BUILD)/$(TARGET).nro: $(BUILD)/$(TARGET).elf' >> build/nro/Makefile &&
          cd build/nro &&
          make
        "
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Lime3DS
        path: dist/
