name: Build Lime3DS

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget gnupg build-essential

    - name: Install devkitPro
      run: |
        wget https://apt.devkitpro.org/install-devkitpro-pacman
        chmod +x install-devkitpro-pacman
        echo "Y" | sudo ./install-devkitpro-pacman
        sudo dkp-pacman -Sy --noconfirm
        sudo dkp-pacman -S switch-dev --noconfirm

    - name: Create build directory
      run: mkdir -p build

    - name: Copy JavaScript files
      run: cp resources/scripts/htmlimporter.js build/

    - name: Create C/C++ wrapper
      run: |
        echo '#include <emscripten.h>' > build/wrapper.cpp
        echo 'extern "C" {' >> build/wrapper.cpp
        echo 'void EMSCRIPTEN_KEEPALIVE run_js() {' >> build/wrapper.cpp
        echo '  // Call your JavaScript function here' >> build/wrapper.cpp
        echo '}' >> build/wrapper.cpp
        echo '}' >> build/wrapper.cpp

    - name: Compile to .so
      run: |
        source ./emsdk/emsdk_env.sh
        emcc -O3 -s WASM=1 -s SIDE_MODULE=1 -o dist/lime3ds.so build/wrapper.cpp build/htmlimporter.js

    - name: Compile to .nro
      run: |
        # Add your specific commands to compile to .nro here
        # Example: Use nx-hbmenu or other tools to package the JavaScript as a homebrew app

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Lime3DS
        path: dist/
